
    var string="EJEMPLOS DE LOS TIPOS DE DATOS DIVERSOS"; 
    var int=25; 
    var float=50.050; 
    var boolean=true; 
    var boolean2=false; 
    var undefined; 
    
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+string + "' Variable String");
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+int + "' Variable Int");
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+float + "' Variable Float ");
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+boolean + "' Variable Booleana");
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+boolean2 + "' Variable Booleana");
    document.write("<br>");
    document.write("<br>");
    document.write("<br>");
    document.write("   '"+undefined + "' Variable Indefinida ");